config/routes.rb
Calendar::Application.routes.draw do
  resources :events do
    collection do
      get 'events_by_day/:date', :action => 'events_by_day', :as => 'events_by_day'

      get 'new_with_date/:date', :action => 'new_with_date', :as => 'new_with_date'
    end
  end

  root :to => "events#index"
  devise_for :users
  resources :users
  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :participants
end

app/models/participant.rb
class Participant < User
   has_and_belongs_to_many :events
   
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :avatar, AvatarUploader     
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
	
	protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :avatar, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :avatar, :remove_image) }
  end
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  

  # GET /events
  # GET /events.json
  def index
    monthrender
  end

  # GET /events/1
  # GET /events/1.json
  def show
    
  end

  # GET /events/new
  def new
    @event = Event.new
        respond_to do |format|
        format.html {  }
        format.js { render 'events/_jsform' }
      
    end
    
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.participants << Participant.find(current_user.id)
    respond_to do |format|
      if @event.save
        monthrender
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
        format.js { render action: 'create' }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
  
  def events_by_day
    @events = Event.where('extract(month from eventdate) = ? AND extract(day from eventdate) = ?', params[:date].to_datetime.month, params[:date].to_datetime.day)
    @date = params[:date]
    respond_to do |format|
      format.html {  }
      format.json { head :no_content }
      format.js {  }
    end    
  end
  
  def new_with_date
    @event = Event.new
    @date = params[:date]
        respond_to do |format|
        format.html {  }
        format.js {  }
      
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :eventdate, :text, :date, :participant_ids => []) if params[:event]
    end
    
    def monthrender
      @events = Event.all
      @events_by_date = @events.group_by { |m| m.eventdate.to_datetime.beginning_of_day }
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:avatar, :name, :bio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def calendar(date = Date.today, &block)
    Calendar.new(self, date, block).table
  end

  class Calendar < Struct.new(:view, :date, :callback)
    HEADER = %w[Monday Monday Tuesday Wednesday Thursday Friday Sunday]
    START_DAY = :monday

    delegate :content_tag, to: :view

    def table
      content_tag :table, class: "calendar" do
        header + week_rows
      end
    end

    def header
      content_tag :tr do
        HEADER.map { |day| content_tag :th, day }.join.html_safe
      end
    end

    def week_rows
      weeks.map do |week|
        content_tag :tr do
          week.map { |day| day_cell(day) }.join.html_safe
        end
      end.join.html_safe
    end

    def day_cell(day)
      content_tag :td, view.capture(day, &callback), class: day_classes(day), id: day
    end

    def day_classes(day)
      classes = []
      classes << "today" if day == Date.today
      classes << "notmonth" if day.month != date.month
      classes << 'td'
      classes.empty? ? nil : classes.join(" ")
    end

    def weeks
      first = date.beginning_of_month.beginning_of_week(START_DAY)
      last = date.end_of_month.end_of_week(START_DAY)
      (first..last).to_a.in_groups_of(7)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event_participants.html.erb
<ul>
<% @event.participants.each do |p| %>
  <li><%= p.name %>
      <%= image_tag p.avatar_url(:thumb).to_s.gsub(/participant/, 'user'), :class => 'preview', :size => '50' if p.avatar %>
  </li>
<% end %>
</ul>

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:remote => true}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <div id="datetimepicker1" class="input-append date">
    <%= f.label :eventdate %><br>
    <%  if @date %>
      <%= f.text_field :eventdate, :value => @date.to_datetime.strftime("%Y-%m-%d %H:%M:%S").to_s, 'data-format'=>"yyyy-MM-dd hh:mm:ss" %>
    <% else %>
      <%= f.text_field :eventdate, 'data-format'=>"yyyy-MM-dd hh:mm:ss" %>
    <% end %>
      <span class="add-on">
        <i data-time-icon="icon-time" data-date-icon="icon-calendar">
        </i>
      </span>
    </div>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
  <%= f.select :participant_ids, Participant.where.not(:id => @event.user_id).collect {|x| [x.email, x.id]}, {}, :multiple => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/_jsform.js.erb
$(".modal-body").html("<%= escape_javascript( render :partial => 'events/form', :event => @event, :date => @date) %> ");

app/views/events/_monthrender.html.erb
  <div id="<%= @date.strftime("%Y-%m") %>">
    <h2 id="month">

      <%= @date.strftime("%B %Y") %>

    </h2>
    <%= calendar @date do |date| %>
      <%= date.day %>

      <% if @events_by_date[date] %>
        <div class="evented">
        <ul>
          <% @events_by_date[date].each do |event| %>
            <li><%= event.name %></li>
          <% end %>
        </ul>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/events/_popup.html.erb
<% events = @events.to_a %>
<table class="table">
<% events[0..4].each do |event| %>
  <tr>
    
    <td><p class="btn pop" id ="<%= event.id %>" data-placement="right" data-trigger="hover" data-toggle="popover" data-content=" " data-original-title="participants"><%= event.name %></p></td>
    <td><p><small><%= event.eventdate.strftime("%H:%M:%S") %></small></p>
        <p><small><%= event.text %></small></p></td>
    <td><p><small><%= event.user.email %></small></p></td>
    <td><p><small><%= image_tag event.user.avatar_url(:thumb).to_s, :class => 'preview', :size => '50' if event.user.avatar %></small></p></td>
    
  </tr>
<% end %>
</table>
<%= link_to 'New Event', new_with_date_events_path(@date), :remote => true %>

app/views/events/create.js.erb
$('.modal').modal('toggle');
$('#<%= @date.strftime("%Y-%m").to_s  %>').html("<%= escape_javascript( render :partial => 'events/monthrender', :date => @date, :events_by_date => @events_by_date ) %>");
$('.evented').parent().closest('td').addClass('evented'); 

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/events_by_day.js.erb
$(".modal-body").html("<%= escape_javascript( render :partial => 'events/popup', :events => @events, :date => @date) %> ");
$('.modal').modal('toggle');
$(".modal-footer").html("<%= @date %> ");
$(".h3modal").html("<%= escape_javascript  @date.to_date.strftime("%Y %B %d") %> events");

app/views/events/index.html.erb
<div id="articles">
<%= render :partial => 'events/monthrender', :date => @date, :events_by_date => @events_by_date %>

</div>

<br>

<%= link_to 'New Event', new_event_path %>

    <div class="modal hide fade">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="h3modal">Modal header</h3>
    </div>
    <div class="modal-body">
    <p>One fine body…</p>
    </div>
    <div class="modal-footer">

    </div>
    </div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/new_with_date.html.erb
<%= render 'form' %>

app/views/events/new_with_date.js.erb
$('.modal').modal('toggle');
setTimeout(
  function() 
  {
   $('.modal').modal('toggle'); 
   $(".modal-body").html("<%= escape_javascript( render :partial => 'events/form', :event => @event, :date => @date) %> ");
   $('#datetimepicker1').datetimepicker({ language: 'en' });
   $(".bootstrap-datetimepicker-widget").css('z-index', '9999');
  }, 500);

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Eventdate:</strong>
  <%= @event.eventdate %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user.email %>
</p>

<ul>
<% @event.participants.each do |p| %>
  <li><%= p.email %>
      <%= image_tag p.avatar_url(:thumb).to_s.gsub(/participant/, 'user'), :class => 'preview', :size => '50' if p.avatar %>
  </li>
<% end %>
</ul>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/show.js.erb
$(".popover-content").html("<%= escape_javascript( render :partial => 'events/event_participants', :event => @event) %> ");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Table</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'http://code.jquery.com/jquery-latest.min.js' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
	<% if user_signed_in? %>
		<%= current_user.email %>
		<%= link_to 'edit pofile', edit_user_registration_path %>
		<%= link_to 'log out', destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to 'sign up', new_user_registration_path %>
		<%= link_to 'log in', new_user_session_path %>
	<% end %>
	
</div>



<%= yield %>



</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= image_tag @user.avatar, :class => 'preview', :size => '50' if @user.avatar %>
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Name</th>
      <th>Bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.avatar %></td>
        <td><%= user.name %></td>
        <td><%= user.bio %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Avatar:</strong>
  <%= @user.avatar %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @user.bio %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>